#!/bin/bash
#
# check code / props for lingering dev flags

codepath="/lv1/collab/code"
configpath="/lv1/collab/config"

if [[ "$1" != "" ]]; then
  if [[ -d "$1" ]]; then
    codepath="$1"
  fi
fi

egrep -ori "(kdebug|kwork)" $codepath | egrep -v "/(\.git|target)/"
